export default {
    SEARCH_RECIPE: "SEARCH_RECIPE",
    GET_RECIPE_DETAIL: "GET_RECIPE_DETAIL",
    NEXT_PAGE: "NEXT_PAGE",
    PREV_PAGE: "PREV_PAGE",
    SET_LOADING: "SET_LOADING",
    BOOKMARK_RECIPE: "BOOKMARK_RECIPE",
};
